apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: task-mgt-dev
  name: batch-job-every-fifteen-minutes
spec:
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: gcr.io/peter-sandbox-237917/task_mgt:v8
            command:
              - flask
            args:
              - tester
              - word
              - "CRON JOB WORKS!"
