apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: task-mgt-dev
  name: task-mgt-flower
  labels:
    app: task-mgt-flower
spec:
  selector:
    matchLabels:
      app: task-mgt-flower
  template:
    metadata:
      labels:
        app: task-mgt-flower
    spec:
      containers:
        - name: task-mgt-flower
          image: gcr.io/peter-sandbox-237917/task_mgt:v7
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: REDIS_HOST
              value: "task-mgt-redis-master"
            - name: REDIS_PORT
              value: "6379"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"
            - name: RABBIT_HOST
              value: "task-mgt-rabbit"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_VHOST
              value: "/"
            - name: CELERY_BACKEND_REDIS_DB
              value: "1"
          command:
            - flower
          args:
            - "--broker=amqp://$(RABBIT_USER):$(RABBIT_PASSWORD)@$(RABBIT_HOST):$(RABBIT_PORT)/$(RABBIT_VHOST)"
            - --loglevel=info
            - --port=80
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: task-mgt-dev
  name: flower-service
  labels:
    app: task-mgt-flower
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: task-mgt-flower
