apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: task-mgt-dev
  name: task-mgt-rabbit
spec:
  selector:
    matchLabels:
      app: task-mgt-rabbit
  replicas: 1
  template:
    metadata:
      labels:
        app: task-mgt-rabbit
    spec:
      containers:
        - name: task-mgt-rabbit
          image: rabbitmq:latest
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 5672
              protocol: TCP  # This is the default?
---
apiVersion: v1
kind: Service
metadata:
  namespace: task-mgt-dev
  name: task-mgt-rabbit
  labels:
    app: task-mgt-rabbit
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: task-mgt-rabbit
