apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: task-mgt-dev
  name: task-mgt-redis-master
spec:
  selector:
    matchLabels:
      app: task-mgt-redis
      role: master
  replicas: 1
  template:
    metadata:
      labels:
        app: task-mgt-redis
        role: master
    spec:
      containers:
        - name: task-mgt-redis-master
          image: redis:latest
          readinessProbe:
          # NOTE: readinessProbe does not restart the container. It will mark
          # the container as "Not Ready". This means the container will also
          # stop receiving requests.
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5 # not default, how long before running the first probe
            periodSeconds: 10  # default, how often the probe runs
            timeoutSeconds: 1  # default, probe should finish within 1 second
            successThreshold: 1  # default, how many probes before considered success
            failureThreshold: 3  # default, how many probes before considered fail
          livenessProbe:
          # NOTE: livenessProbe will restart the container if it fails 3 times in a row (default)
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5  # not default, how long before running the first probe
            periodSeconds: 10  # default, how often the probe runs
            timeoutSeconds: 1  # default, probe should finish within 1 second
            successThreshold: 1  # default, how many probes before considered success
            failureThreshold: 3  # default, how many probes before considered fail
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 500m
              memory: 100Mi
          ports:
            - containerPort: 6379
              protocol: TCP  # This is the default?
---
apiVersion: v1
kind: Service
metadata:
  namespace: task-mgt-dev
  name: task-mgt-redis-master
  labels:
    app: task-mgt-redis
    role: master
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: task-mgt-redis
    role: master
