apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: task-mgt-dev
  name: task-mgt-worker-default
  labels:
    app: task-mgt-worker-default
spec:
  selector:
    matchLabels:
      app: task-mgt-worker-default
  template:
    metadata:
      labels:
        app: task-mgt-worker-default
    spec:
      containers:
        - name: task-mgt-worker-default
          image: gcr.io/peter-sandbox-237917/task_mgt:VERSION
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: REDIS_HOST
              value: "task-mgt-redis-master"
            - name: REDIS_PORT
              value: "6379"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"
            - name: RABBIT_HOST
              value: "task-mgt-rabbit"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_VHOST
              value: "/"
            - name: CELERY_BACKEND_REDIS_DB
              value: "1"
          ports:
            containerPort: 80
          command: celery -A app.celery worker -Q celery --loglevel=info -n default@%h
